version: '3.5'
services:
  postgres:
    container_name: swc_postgres
    image: postgres
    environment:
      POSTGRES_USER: swcapi
      POSTGRES_PASSWORD: password12@
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
volumes:
  postgres: